### ISSUE TITLE
ISSUE: Atom Notification Info 

### ISSUE THREAD

**Issue by cyberea** [fstiewitz/build-tools-cpp#81]
Hello,

I have been encountering an issue whereby the info notification would not render correctly upon loading up Atom.

I thought I would wait as normally version updates tend to squash these thing for me, but nothing really happened for some time. So I decided to investigate.

## ISSUE
![build-notification-issue](https://user-images.githubusercontent.com/4736815/27537098-2d731e02-5a6a-11e7-9a6c-1192fcfe98b2.gif)

## FORKED BRANCH
https://github.com/cyberea/build-tools-cpp/commit/67d1508f73e19ad603a8a61a27d859bce867c768

I didn't want to submit a PR without writing at least something here first, because it might just be my current Atom setup. Nevertheless, the branch is there if you feel its legit.

Thanks! :)

**Comment by LeastSignificantBit** [comment]
In addition to cyberea@67d1508 fix, the following `&:hover {` section seems to cause problems.
I removed it and all works well now.

**Comment by fstiewitz** [comment]
Sorry for not replying. I kinda stopped using atom long ago, so this repo is low priority for me. If you submit a PR I'd apply it :)

**Comment by LeastSignificantBit** [comment]
Ok, done
https://github.com/fstiewitz/build-tools-cpp/pull/85#issue-270627912
